import { db, schema } from './index.js';

const seedOffices = [
  {
    address: 'Sveavägen 42',
    area: 'Norrmalm',
    city: 'Stockholm',
    lat: '59.3387',
    lng: '18.0552',
    sqm: 250,
    rooms: 8,
    estimatedRent: 62500,
    rentMin: 58000,
    rentMax: 67000,
    rentPerSqm: '250',
    type: 'office',
    culture: 'modern',
    priceLevel: 'premium',
    verified: true,
    newlyRenovated: true,
    flexibleContract: true,
    amenities: ['Pentry', 'Dusch', 'Fiber', 'Gym', 'Reception', 'Balkong'],
    images: ['/images/office1.jpg'],
    description: 'Ljust och modernt kontorslandskap i hjärtat av Stockholm.',
    metroDistance: 2,
    restaurantRating: '5',
    greenSpaceRating: '3',
    buildingYear: 1965,
    owner: 'Vasakronan',
    nearbyCompanies: ['Spotify', 'Klarna', 'TechStartup AB'],
    source: 'vasakronan',
  },
  {
    address: 'Hornsgatan 82',
    area: 'Södermalm',
    city: 'Stockholm',
    lat: '59.3171',
    lng: '18.0494',
    sqm: 120,
    rooms: 4,
    estimatedRent: 33600,
    rentMin: 30000,
    rentMax: 37000,
    rentPerSqm: '280',
    type: 'office',
    culture: 'modern',
    priceLevel: 'standard',
    verified: true,
    newlyRenovated: false,
    flexibleContract: true,
    amenities: ['Pentry', 'Fiber', 'Cykelparkering', 'Terrass'],
    images: ['/images/office2.jpg'],
    description: 'Kreativt kontor i populärt läge på Södermalm.',
    metroDistance: 4,
    restaurantRating: '5',
    greenSpaceRating: '4',
    buildingYear: 1920,
    owner: 'Einar Mattsson',
    nearbyCompanies: ['Designbyrå X', 'PR-byrå Y'],
    source: 'direktkontor',
  },
  {
    address: 'Isafjordsgatan 15',
    area: 'Kista',
    city: 'Stockholm',
    lat: '59.4048',
    lng: '17.9443',
    sqm: 450,
    rooms: 15,
    estimatedRent: 76500,
    rentMin: 70000,
    rentMax: 83000,
    rentPerSqm: '170',
    type: 'office',
    culture: 'modern',
    priceLevel: 'budget',
    verified: true,
    newlyRenovated: true,
    flexibleContract: false,
    amenities: ['Pentry', 'Dusch', 'Fiber', 'Parkering', 'Gym', 'Reception'],
    images: ['/images/office3.jpg'],
    description: 'Rymligt kontor i Kista Science City.',
    metroDistance: 3,
    restaurantRating: '3',
    greenSpaceRating: '4',
    buildingYear: 2005,
    owner: 'Klövern',
    nearbyCompanies: ['Ericsson', 'Microsoft', 'IBM'],
    source: 'castellum',
  },
  {
    address: 'Strandvägen 7A',
    area: 'Östermalm',
    city: 'Stockholm',
    lat: '59.3315',
    lng: '18.0840',
    sqm: 180,
    rooms: 6,
    estimatedRent: 63000,
    rentMin: 58000,
    rentMax: 68000,
    rentPerSqm: '350',
    type: 'office',
    culture: 'traditional',
    priceLevel: 'premium',
    verified: true,
    newlyRenovated: false,
    flexibleContract: false,
    amenities: ['Pentry', 'Fiber', 'Reception', 'Parkering'],
    images: ['/images/office4.jpg'],
    description: 'Prestigefullt kontor på Strandvägen med utsikt.',
    metroDistance: 8,
    restaurantRating: '4',
    greenSpaceRating: '5',
    buildingYear: 1890,
    owner: 'Humlegården Fastigheter',
    nearbyCompanies: ['Advokatfirma A', 'Fondbolag B'],
    source: 'humlegarden',
  },
  {
    address: 'Östra Hamngatan 16',
    area: 'Centrum',
    city: 'Göteborg',
    lat: '57.7055',
    lng: '11.9669',
    sqm: 200,
    rooms: 7,
    estimatedRent: 40000,
    rentMin: 36000,
    rentMax: 44000,
    rentPerSqm: '200',
    type: 'office',
    culture: 'modern',
    priceLevel: 'standard',
    verified: true,
    newlyRenovated: false,
    flexibleContract: true,
    amenities: ['Pentry', 'Fiber', 'Reception', 'Gym'],
    images: ['/images/office7.jpg'],
    description: 'Centralt beläget kontor i Göteborgs hjärta.',
    metroDistance: 3,
    restaurantRating: '5',
    greenSpaceRating: '2',
    buildingYear: 1975,
    owner: 'Castellum',
    nearbyCompanies: ['E-handelsbolag A', 'Fintech B'],
    source: 'castellum',
  },
  {
    address: 'Malmöhusvägen 1',
    area: 'Centrum',
    city: 'Malmö',
    lat: '55.6086',
    lng: '12.9998',
    sqm: 150,
    rooms: 5,
    estimatedRent: 24000,
    rentMin: 21000,
    rentMax: 27000,
    rentPerSqm: '160',
    type: 'office',
    culture: 'modern',
    priceLevel: 'budget',
    verified: true,
    newlyRenovated: true,
    flexibleContract: true,
    amenities: ['Pentry', 'Fiber', 'Cykelparkering', 'Dusch'],
    images: ['/images/office8.jpg'],
    description: 'Modernt kontor nära Malmö C.',
    metroDistance: 5,
    restaurantRating: '4',
    greenSpaceRating: '4',
    buildingYear: 2010,
    owner: 'Wihlborgs',
    nearbyCompanies: ['Gaming Studio X', 'Cleantech Y'],
    source: 'wihlborgs',
  },
];

const seedAreaStats = [
  { name: 'Norrmalm', city: 'Stockholm', avgRentPerSqm: '275', yearChange: '4.2', trend: 'up', totalListings: 156, lat: '59.3345', lng: '18.0632' },
  { name: 'Södermalm', city: 'Stockholm', avgRentPerSqm: '295', yearChange: '3.1', trend: 'up', totalListings: 89, lat: '59.3150', lng: '18.0731' },
  { name: 'Östermalm', city: 'Stockholm', avgRentPerSqm: '340', yearChange: '2.8', trend: 'up', totalListings: 67, lat: '59.3386', lng: '18.0890' },
  { name: 'Kungsholmen', city: 'Stockholm', avgRentPerSqm: '235', yearChange: '1.5', trend: 'stable', totalListings: 112, lat: '59.3328', lng: '18.0289' },
  { name: 'Kista', city: 'Stockholm', avgRentPerSqm: '180', yearChange: '-0.8', trend: 'down', totalListings: 203, lat: '59.4050', lng: '17.9500' },
  { name: 'Centrum', city: 'Göteborg', avgRentPerSqm: '210', yearChange: '2.1', trend: 'up', totalListings: 134, lat: '57.7055', lng: '11.9669' },
  { name: 'Centrum', city: 'Malmö', avgRentPerSqm: '175', yearChange: '1.8', trend: 'up', totalListings: 98, lat: '55.6050', lng: '13.0038' },
];

async function seed() {
  console.log('🌱 Seeding database...');

  try {
    // Insert offices
    for (const office of seedOffices) {
      await db.insert(schema.offices).values(office).onConflictDoNothing();
    }
    console.log(`✅ Inserted ${seedOffices.length} offices`);

    // Insert area stats
    for (const area of seedAreaStats) {
      await db.insert(schema.areaStats).values(area).onConflictDoNothing();
    }
    console.log(`✅ Inserted ${seedAreaStats.length} area stats`);

    console.log('✅ Database seeding completed!');
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }

  process.exit(0);
}

seed();
